all:
	c++ Bureaucrat.cpp AForm.cpp ShrubberyCreationForm.cpp RobotomyRequestForm.cpp PresidentialPardonForm.cpp main.cpp -Wall -Wextra -Werror -std=c++98 -o form -fsanitize=address -g3

clean:
	rm form
	rm -rf form.dSYM
	rm *_shrubbery